name: Auto Assign
on:
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: caleb-sb
          numOfAssignee: 1
      - name: 'Auto-assign to project'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/TheCliffs/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
